version: '3'

services:
  players-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: players-service
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: players
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  flyway:
    image: flyway/flyway
    depends_on:
      - postgres
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres/players
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: password
      FLYWAY_SCHEMAS: public
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./sql:/flyway/sql

